name: Run Unity Tests
on: [ pull_request, workflow_dispatch ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: copy dir to new dir
        run: |
          pwd
          folderName=$(echo "${PWD##*/}")
          rsync -r "$GITHUB_WORKSPACE" "copiedProject" 
          ls -F "copiedProject/$folderName"
      - name: Run tests
        id: runTests
        uses: trudeaua21/unity-test-runner@main
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectPath: ./copiedProject/tezos-unity-sdk
          unityVersion: "2021.3.20f1"
          testMode: all
#          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+tezos-unity-sdk.*,-*Tests*'
          packageMode: true

      # Upload coverage
      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Package Coverage results (all)
          path: ${{ steps.runTests.outputs.coveragePath }}
          retention-days: 1